import clipboard from "../../assets/pictures/icons/clipboard-icon.png";
import chat from "../../assets/pictures/icons/dark-chat-icon.png";
import diamond from "../../assets/pictures/icons/diamond-icon.png";
import mail from "../../assets/pictures/icons/mail-icon.png";
import upArrow from "../../assets/pictures/icons/up-arrow-icon.png";

import illustrator from "../../assets/pictures/logos/ai_icon.png";
import css from "../../assets/pictures/logos/css3-logo.png";
import eclipse from "../../assets/pictures/logos/eclipse-logo.png";
import figma from "../../assets/pictures/logos/figma-logo.png";
import gitHub from "../../assets/pictures/logos/github-logo.png";
import html from "../../assets/pictures/logos/html5-logo.png";
import java from "../../assets/pictures/logos/java-logo.png";
import linkedin from "../../assets/pictures/logos/linkedin-logo.png";
import nextjs from "../../assets/pictures/logos/nextjs-icon.png";
import php from "../../assets/pictures/logos/php-logo.png";
import reactjs from "../../assets/pictures/logos/reactjs-logo.png";
import sass from "../../assets/pictures/logos/sass-logo.png";
import vscode from "../../assets/pictures/logos/vscode-logo.png";
